k9s:
  liveViewAutoRefresh: true
  screenDumpDir: /tmp/k9s/screen-dumps
  refreshRate: 2
  maxConnRetry: 5
  readOnly: true
  noExitOnCtrlC: false
  ui:
    skin: catppuccin-latte-transparent
    enableMouse: false
    headless: true
    logoless: false
    crumbsless: false
    splashless: false
    reactive: true
    noIcons: false
    defaultsToFullScreen: false
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: true
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
